version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///database_file/users.db
      - SECRET_KEY=dev_secret_key
      - UPLOAD_FOLDER=/app/uploads
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - ./database_file:/app/database_file
      - ./:/app  # Mount the entire app directory for development

# Remove PostgreSQL service and volume since we're using SQLite