apiVersion: apps/v1
kind: Deployment
metadata:
  name: freelance-app
  namespace: production
spec:
  replicas: 3  # Increased replicas for higher availability in prod
  selector:
    matchLabels:
      app: freelance
  template:
    metadata:
      labels:
        app: freelance
    spec:
      containers:
      - name: app
        image: youssefashraf265/flask-example-master_web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL        
          value: "postgresql://flaskuser:yourpassword@postgres/flask_app_production"
        - name: FLASK_ENV
          value: "production"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
      # imagePullSecrets:
      # - name: gitlab-registry  # Commented out GitLab-specific part